<?php
$country = array( " Afghanistan " => " Kabul " , " Albania " => " Tirana " , " Algeria " => " Algiers " ,
 " Andorra " => " Andorra La Vella " , " Angola " => " Luanda " ,
 " Antigua and Barbuda " => " Saint John's " ,
 " Argentina " => " Buenos Aires" , " Armenia " => " Yerevan " , " Australia " => " Canberra " ,
 " Austria " => " Vienna " , " Azerbaijan " => " Baku " , " Bahamas " => " Thenassau " , " Bahrain " => " Manama " ,
 " Bangladesh " => " Dhaka " , " Barbados " => " Bridgetown " , " Belarus " => " Minsk " , " Belgium " => " Brussels " ,
 " Belize " => " Belmopan " , " Benin " => " Porto Novo " , " Bhutan " => " Sucre " ,
 " Bolivia " => " Sucre " , " Bosnia and Herzegovina " => " Sarajevo " , " Botswana " => " Gaborone " ,
 " Brazil " => " Brasilia " ,
 " Brunei " => " Bandar Seri Begawan " , " Bulgaria " => " Sofia " , " Burkina Faso " => " Ouagadougou " , " Burundi " => " Bujumbura Cabo Verde Praia" ,
 " Cambodia " => " Phnom Penh " , " Cameroon " => " Yaounde " , " Canada " => " Ottawa " ," Central African Republic " => " Bangui " ,
 " Chad " => " DJamena " , " Chile " => " Santiago " , " China " => " Beijing " ," Colombia " => " Bogota " , " Comoros " => " Moroni " ,
 " Congo - Brazzaville " => " Democratic Republic of Thekinshasa " , " Costa Rica " => " San Jose " , " Croatia " => " Zagreb " , " Cuba " => " Havana " , " Cyprus " => " Nicosia " ,
 " Czech Republic " => " Prague " , " Denmark " => " Copenhagen " ,
 " Djibouti " => " Djibouti " , " Dominica " => " Roseau " , " Dominican Republic " => " Santo Domingo " ,
 " Ecuador " => " Quito " ,
 " Egypt " => " Cairo " , " El Salvador " => " San Salvador " , " Equatorial Guinea " => " Malabo " ,
 " Eritrea " => " Asmara " , " Estonia " => " Tallinn Eswatinimbabane " , " Ethiopia " => " Addis Ababa " ,
 " Fiji " => " Suva " , " Finland " => " Helnski " , " France " => " Paris " ,
 " Gabon " => " Libreville " ,
 " Gambia " => " The Banjul " , " Georgia " => " Tbilisi " , " Germany " => " Berlin " , " Ghana " => " Accra " ,
 " Greece " => " Athens " , " Grenada " => " Saint George's" , " Guatemala " => " Guatemala City " ,
 " Guinea " => " Conakry " ,
 " Guinea-Bissau " => " Guinea-Bissau " , " Guyana " => " George town " , " Haiti " => " Port Au Prince " ,
 " Honduras " => " Tegucigalpa " , " Hong Kong SAR China " => " Hongkong " , " Hungary " => " Budapest " ,
 " Iceland " => " Reykjavik " , " India " => " New Delhi " , " Indonesia " => " Jakarta " , " Iran " => " Tehran " ,
 " Iraq " => " Baghdad " , " Ireland " => " Dublin " , " Israel " => " Jerusalem " ,
 " Italy " => " Rome " , " Jamaica " => " Kingston " , " Japan " => " Tokyo " , " Jordan " => " Amman " , " Kazakhstan " => " Astana " ,
 " Kenya " => " Nairobi " , " Kiribati " => " South Tarawa " , " Kuwait " => " Kuwait City " , " Kyrgyzstan " => " Bishkek " ,
 " Laos " => " Vientiane " , " Latvia " => " Riga " , " Lebanon " => " Beirut " , " Lesotho " => " Maseru " ,
 " Liberia " => " Monrovia " , " Libya " => " Tripoli " , " Liechtenstein " => " Vaduz " ,
 " Lithuania " => " Vilnius " , " Luxembourg " => " Luxembourg " , " Madagascar " => " Antananarivo " , " Malawi " => " Lilongwe " ,
 " Malaysia " => " Kuala Lumpur " , " Maldives " => " Male " , " Mali " => " Bamako " , " Malta " => " Valletta " ,
 " Marshall Islands " => " Majuro " , " Mauritania " => " Noukchott " ,
 " Mauritius " => " Port Louis " , 
 " Mexico " => " Mexico City " ,
 " Moldova " => " Chisinau " , " Monaco " => " Monaco " , " Mongolia " => " Ulaanbaatar " , " Montenegro " => " Podgorica" ,
 " Morocco " => " Rabat " , " Mozambique " => " Maputo " ,
 " Myanmar [Burma] " => " Nay Pyi Taw " , " Namibia " => " Windhoek " , " Nauru " => " Yaren District" ,
 " Nepal " => " Kathmadu " , " Netherlands " => " Amsterdam " ," New Zealand " => " Wellington " ,
 " Nicaragua " => " Managua " , " Niger " => " Niamey " , " Nigeria " => " Abuja " , " North Korea " => " Pyongyang " ,
 " Northern Macedonia " => " Skopje " , " Norway " => " Oslo " , " Oman " => " Muscat " ,
 " Pakistan " => " Islamabad " ,
 " Palau " => " Ngerulmud " , " Palestinian Territories " => " Jerusalem " , " Panama " => " Panama City " ,
 " Papua New Guinea " => " Papua New Guinea Port Moresby " , " Paraguay " => " Asuncion " ,
 " Peru " => " Lima " ,
 " Philippines " => " Manila " , " Poland " => " Warsaw " ,
 " Portugal " => " Lisbon " , " Puerto Rico " => " San Juan " , " Qatar " => " Doha " , " Romania " => " Bucharest " ,
 " Russia " => " Moscow " , " Rwanda " => " Kigali " ," Saint Kitts and Nevis " => " Basseterre " , " Saint Lucia " => " Castries " ,
 " Saint Vincent and the Grenadines " => " Kingstown " , " Samoa " => " Apia " ,
 " San Marino " => " San Marino " , " Saudi Arabia " => " Riyadh " , " Senegal " => " Dakar " ,
 " Serbia " => " Belgrade " , " Seychelles " => " Victoria " ,
 " Sierra Leone " => " Freetown " , " Singapore " => " Singapore " , " Slovakia " => " Brastislava " ,
 " Slovenia " => " Ljubljana " , " Solomon Islands " => " Shioniara " , " Somalia " => " Mogadishu " ,
 " South Africa " => " Cape town " ,
 " South Korea " => " Seoul " , " Spain " => " Madrid " , " Sri Lanka " => " Sri Colombo " , " Sudan " => " Khartoum " ,
 " Suriname " => " Paramaribo " ," Switzerland " => " Bern " , " Syria " => " Damascus " , 
 " Taiwan " => " Taiwan " , " Tajikistan " => " Dushanbe " , " Tanzania " => " Dodoma " , " Thailand " => " Bangkok " ,
 " Timor-Leste " => " Dili " , " Togo " => " Lome " , " Tonga " => " Nuku'alofa " ,
 " Trinidad and Tobago " => " Port of Spain " , " Tunisia " => " Tunis " , " Turkey " => " Ankara " ,
 " Turkmenistan " => " Ashgabat " , " Tuvalu " => " Funafuti " ,
 " Uganda " => " Kampala " , " Ukraine " => " Kiev " ,
 " United Arab Emirates " => " Abu Dhabi " ,
 " United Kingdom " => " London " , " United States " => " Washington " ,
 " Uruguay " => " Montevideo " , " Uzbekistan " => " Tashkent " , " Vanuatu " => " Port Villa " , " Vatican City " => " Vatican City " ,
 " Venezuela " => " Caracas " , " Vietnam " => " Hanoi " , " Yemen " => " Sana A " , " Zambia " => " Lusaka " , " Zimbabwe " => " Harabe " ,);
 foreach ($country as $x => $x_value) {
    echo "" . $x . "-" . $x_value;
    echo "<br>";
}
 ?>